/**
 * GX-ID — Global configuration
 *
 * This file holds every user-tunable value. Runtime secrets that should not be
 * committed belong in `.env` (see `.env.example`).
 */
import { getDatabase } from "./lib/database.js";
import { GX_CORE_CONFIG } from "./GX.js";
import xmppConfig from "./config/xmpp.js";

function env(key, fallback = undefined) {
  const value = process.env[key];
  return value === undefined || value === "" ? fallback : value;
}

function envList(key, fallback = []) {
  const value = env(key);
  if (!value) return fallback;
  return String(value)
    .split(",")
    .map((v) => v.replace(/[^0-9]/g, ""))
    .filter(Boolean);
}

const config = {
  bot: {
    name: env("BOT_NAME", "GX-ID"),
    shortName: "GX",
    version: "1.0.0",
    developer: env("BOT_DEVELOPER", "GeneticID"),
    number: env("BOT_NUMBER", ""),
    support: env("BOT_SUPPORT", ""),
  },

  owner: {
    name: env("OWNER_NAME", "Owner"),
    number: envList("OWNER_NUMBER", []),
  },

  session: {
    folderName: env("SESSION_FOLDER", "session"),
    usePairingCode: env("USE_PAIRING_CODE", "true") === "true",
    // Phone number (digits only, with country code) used to request the pairing
    // code. Falls back to `bot.number` when empty.
    pairingNumber: env("PAIRING_NUMBER", ""),
    // Optional 8-char custom pairing code (Crockford base32 — no I, L, O, U).
    // When empty or invalid a random code is generated by Baileys.
    pairingCode: env("PAIRING_CODE", ""),
    printQRInTerminal: env("PRINT_QR", "true") === "true",
    maxReconnectAttempts: 5,
    reconnectInterval: 15000,
  },

  mode: env("BOT_MODE", "public"),

  /**
   * Message gate — controls which incoming messages the bot reacts to.
   * `bootGraceMs` is the tolerance (ms) applied to the "online since" boundary:
   * messages older than that are treated as pre-boot (queued while offline) and
   * are ignored. Raise it on hosts with a skewed clock.
   */
  messageGate: {
    bootGraceMs: Number(env("MESSAGE_BOOT_GRACE_MS", "5000")),
  },

  command: {
    prefix: env("PREFIX", "."),
    caseSensitive: false,
  },

  features: {
    antiCall: false,
    blockIfCall: false,
    autoTyping: true,
    autoRead: true,
    logMessage: true,
    antiSpam: true,
  },

  registration: {
    enabled: false,
  },

  database: {
    path: env("DATABASE_PATH", "./database/main"),
  },

  /**
   * Channel / newsletter used for the "forwarded from channel" preview.
   * Leave the jid empty to disable the channel tag entirely.
   */
  channel: {
    id: env("CHANNEL_ID", ""),
    name: env("CHANNEL_NAME", "GX-ID Channel"),
    link: env("CHANNEL_LINK", ""),
  },

  /**
   * Assets. Values may be a local path (relative to project root) or a remote
   * URL. Remote URLs are fetched once during boot by the asset manager.
   * Missing assets fall back to generated placeholders so the menu never breaks.
   */
  assets: {
    menu: env("ASSET_MENU", ""),
    thumb: env("ASSET_THUMB", ""),
    audio: env("ASSET_AUDIO", ""),
    ...structuredClone(GX_CORE_CONFIG.assets),
  },

  ui: {
    menuVariant: 2,
    allmenuVariant: 2,
    sendMenuAudio: false,
  },

  sticker: {
    packname: env("STICKER_PACK", "GX-ID"),
    author: env("STICKER_AUTHOR", "GX-ID"),
  },

  messages: {
    /**
     * Silent mode — master switch for the feedback notices below: the messages
     * the bot sends when it *refuses* or *cannot* run a command (unknown
     * command, command disabled, owner-only, group-only, admin-only, cooldown,
     * ban, unregistered group, …).
     *
     *   silent: true    → send nothing (or react — see `onDisabled`)
     *   silent: false   → send the configured text (normal behaviour)
     *
     * This is the CONFIG DEFAULT. The owner can override it at runtime with
     * `.silent on|off`, which persists in the database and takes precedence.
     * The legacy `enabled` flag is still honoured when present (`enabled: false`
     * means silent mode ON).
     *
     * Functional command output (`wait`, `success`, `error`, `genericError`)
     * and the bare-command usage/help cards are NOT affected — silencing those
     * would break the commands that rely on them.
     */
    silent: env("MESSAGES_SILENT", "true") === "true",
    /**
     * What to do while silent mode is ON:
     *   "silent" → send nothing at all
     *   "react"  → react to the triggering message with `react` below
     */
    onDisabled: "silent",
    /** Emoji used when `onDisabled` is "react". */
    react: "🔒",

    wait: "🕕 *Processing…* please wait a moment.",
    success: "✅ *Done!*",
    error: "❌ *Something went wrong.* Please try again later.",

    ownerOnly: "*Owner only.* This command is restricted to the bot owner.",
    premiumOnly: "*Premium only.* You need premium access to use this.",
    groupOnly:
      "*Group only.* This command can only be used inside a group.",
    privateOnly: "*Private only.* Use this command in a private chat.",
    adminOnly: "*Admin only.* You must be a group admin to use this.",
    botAdminOnly: "*Bot must be an admin* to perform this action.",

    cooldown: "🕕 *Cooldown.* Wait %time% more second(s) before using this again.",
    banned: "🚫 *You are banned* from using this bot.",
    rejectCall: "🚫 *Please don't call the bot.* Send a message instead.",
    //❓ Command not found.
    notFound: "",
    groupOnlyExplicit: "❌ Perintah ini hanya dapat digunakan di dalam grup.",
    //🔒 *Grup belum terdaftar.* Hubungi owner untuk mendaftarkan grup ini.
    unregisteredGroup: "",
    genericError: "*Error*",
  },

  errorTemplate:
  //⚠️ *GX-ID* hit an error while running `{prefix}{command}`.\n\n> Sorry {pushName}, please try again later.\n> If it keeps happening, contact the owner.
    "",

  dev: {
    enabled: process.env.NODE_ENV === "development",
    watchPlugins: process.env.NODE_ENV === "development",
    debugLog: process.env.NODE_ENV === "development",
  },

  /**
   * Self-update source. The repository is configured through `.env`, never
   * hardcoded here:
   *   GITHUB_REPO          owner/repo | owner/repo#branch | https://github.com/owner/repo
   *   GITHUB_BRANCH        branch/tag/sha override (optional)
   *   GITHUB_TOKEN         personal access token (private repos / rate limits)
   *   UPDATE_AUTO_RESTART  "true" to restart after applying an update
   */
  update: {
    repo: env("GITHUB_REPO", ""),
    branch: env("GITHUB_BRANCH", ""),
    token: env("GITHUB_TOKEN", ""),
    autoRestart: env("UPDATE_AUTO_RESTART", "false") === "true",
  },

  /**
   * WhatsApp ↔ Minecraft bridge. The full definition lives in `config/xmpp.js`
   * (single source of truth, credentials come from `.env`). Exposed here so
   * plugins can read `config.xmpp` alongside the rest of the configuration.
   */
  xmpp: xmppConfig,

  /**
   * Local document → PDF converter (the `/pdf` command) and its inverse, the
   * PDF → document converter (`/unpdf`). Runtime limits are also read directly
   * from `.env` by `lib/pdf-convert.js` / `lib/pdf-export.js` (so they
   * hot-reload); they are mirrored here for discoverability.
   */
  pdf: {
    maxSizeMb: Number(env("PDF_MAX_SIZE_MB", "25")),
    timeoutMs: Number(env("PDF_TIMEOUT_MS", "90000")),
    libreOfficePath: env("LIBREOFFICE_PATH", ""),
    /** How long a PDF→format picker stays valid, in seconds. */
    jobTtlSeconds: Number(env("PDF_JOB_TTL_SECONDS", "900")),
    /** Maximum number of pending PDF→format jobs kept in memory. */
    jobMax: Number(env("PDF_JOB_MAX", "50")),
  },

  /* ───────────────── GX-ID compatibility layer ─────────────────
   * The game subsystem copied from GX-ID (src/lib/GX-*.js, plugins/game)
   * reads a handful of extra config fields. They are mapped onto GX.js and
   * the GX-ID config above so both bots share a single configuration.
   */
  info: structuredClone(GX_CORE_CONFIG.info),
  saluran: structuredClone(GX_CORE_CONFIG.saluran),
  officialGXGroup: structuredClone(GX_CORE_CONFIG.officialGXGroup),
  energi: structuredClone(GX_CORE_CONFIG.energi),
  payment: structuredClone(GX_CORE_CONFIG.payment),
  donasi: structuredClone(GX_CORE_CONFIG.donasi),

  /* Third-party API credentials. Only the keys actually referenced by the code
   * live here; each is read from `.env` so no secret is committed. Unused keys
   * that shipped with GX-ID are kept, commented out, in `.env.example`. */
  APIkey: {
    lolhuman: env("APIKEY_LOLHUMAN", ""),
    neoxr: env("APIKEY_NEOXR", ""),
    fgsi: env("APIKEY_FGSI", ""),
    covenant: env("APIKEY_COVENANT", ""),
    cuki: env("APIKEY_CUKI", ""),
    termaiCdn: env("APIKEY_TERMAICDN", ""),
  },
  apiBase: {
    termaiCdn: env("TERMAI_CDN_BASE", "https://c.termai.cc"),
  },
  telegram: {
    botToken: env("TELEGRAM_BOT_TOKEN", ""),
  },
  pterodactyl: {
    server1: { domain: "", apikey: "", capikey: "", egg: "15", nestid: "5", location: "1" },
    server2: { domain: "", apikey: "", capikey: "", egg: "15", nestid: "5", location: "1" },
    server3: { domain: "", apikey: "", capikey: "", egg: "15", nestid: "5", location: "1" },
    server4: { domain: "", apikey: "", capikey: "", egg: "15", nestid: "5", location: "1" },
    server5: { domain: "", apikey: "", capikey: "", egg: "15", nestid: "5", location: "1" },
  },
};

/* ─────────────────────────── helper functions ─────────────────────────── */

function cleanNumber(value) {
  if (value === undefined || value === null) return "";
  return String(value).split(":")[0].split("@")[0].replace(/[^0-9]/g, "");
}

function numberMatches(a, b) {
  const x = cleanNumber(a);
  const y = cleanNumber(b);
  if (!x || !y) return false;
  return x === y || x.endsWith(y) || y.endsWith(x);
}

function isOwner(number) {
  const target = cleanNumber(number);
  if (!target) return false;

  if (config.bot?.number && numberMatches(target, config.bot.number)) return true;

  if (Array.isArray(config.owner?.number)) {
    if (config.owner.number.some((own) => numberMatches(target, own))) return true;
  }

  try {
    const db = getDatabase();
    if (!db) return false;

    if (Array.isArray(db.data?.owner) && db.data.owner.some((o) => numberMatches(target, o))) {
      return true;
    }
    const extra = db.setting("ownerNumbers");
    if (Array.isArray(extra) && extra.some((o) => numberMatches(target, o))) {
      return true;
    }
  } catch {
    /* database not ready yet */
  }

  return false;
}

function isBanned(number) {
  const target = cleanNumber(number);
  if (!target) return false;
  if (isOwner(target)) return false;

  let list = [];
  try {
    const db = getDatabase();
    list = db.setting("bannedUsers") || [];
  } catch {
    /* ignore */
  }
  return list.some((b) => numberMatches(target, b));
}

/**
 * Premium / partner checks used by the GX game subsystem. Premium status lives
 * in the user record and in the `premiumUsers` / `partnerUsers` settings lists.
 */
function isPremium(number) {
  const target = cleanNumber(number);
  if (!target) return false;
  if (isOwner(target)) return true;

  try {
    const db = getDatabase();
    const user = db.getUser(target);
    if (user?.isPremium) return true;
    const list = db.setting("premiumUsers") || [];
    if (list.some((p) => numberMatches(target, p))) return true;
  } catch {
    /* ignore */
  }
  return false;
}

function isPartner(number) {
  const target = cleanNumber(number);
  if (!target) return false;
  if (isOwner(target)) return true;

  try {
    const db = getDatabase();
    const list = db.setting("partnerUsers") || [];
    if (list.some((p) => numberMatches(target, p))) return true;
  } catch {
    /* ignore */
  }
  return false;
}

function setBotNumber(number) {
  if (number) config.bot.number = cleanNumber(number);
}

function isSelf(number) {
  return numberMatches(number, config.bot.number);
}

function getOwnerName() {
  return config.owner?.name || "Owner";
}

config.isOwner = isOwner;
config.isBanned = isBanned;
config.isPremium = isPremium;
config.isPartner = isPartner;
config.setBotNumber = setBotNumber;
config.isSelf = isSelf;
config.getOwnerName = getOwnerName;

export default config;
export {
  config,
  isOwner,
  isBanned,
  isPremium,
  isPartner,
  setBotNumber,
  isSelf,
  getOwnerName,
  cleanNumber,
  numberMatches,
};
